name = "l4ud/egooe"
version = "0.1.7"
description = "EgooE - A modular UI widget library for Roblox"
authors = ["CapedBojji"]
repository = "https://github.com/CapedBojji/EgooE"
license = "MIT"
includes = ["src/**/*", "pesde.toml", "README.md", "LICENSE"]

[target]
environment = "roblox"
build_files = ["src"]
lib = "src/init.lua"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[indices]
default = "https://github.com/pesde-pkg/index"

[engines]
pesde = "^0.7.0"
