[package]
name = "l4ud/egooe"
version = "0.1.3"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "An immediate-mode UI framework for Roblox with Iris visual style and Plasma-compatible API"
license = "MIT"

[dependencies]
